services:
  - type: web
    name: django-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        value: "postgresql://postgres.fjqbhcmsqypevfbpzcxj:TrackerPass@aws-1-eu-north-1.pooler.supabase.com:5432/postgres"
      - key: SUPABASE_URL
        value: "https://fjqbhcmsqypevfbpzcxj.supabase.co"
      - key: SUPABASE_KEY
        value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqcWJoY21zcXlwZXZmYnB6Y3hqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NDE1NzEsImV4cCI6MjA3MjIxNzU3MX0.QPmyPnP8VbvXYnmfWEumeErBsZjItcVPJv3dwhsJMpc"
      - key: TELEGRAM_BOT_TOKEN
        value: "8300811327:AAFnVMh21kSS7vemrdtdGmnhMjF0npCWNhs"
      - key: TELEGRAM_BOT_NAME
        value: "self_development_tracker_bot"
      - key: ALLOWED_HOSTS
        value: "self-development-tracker.onrender.com,localhost,127.0.0.1"
