services:
  - type: web
    name: django-backend
    env: python
    plan: free
    # Build: устанавливаем зависимости, собираем статику и применяем миграции (fail fast если что-то не так)
    buildCommand: >
      pip install --upgrade pip &&
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput &&
      python manage.py makemigrations --noinput || true &&
      python manage.py migrate --noinput
    # Start: на каждый запуск гарантируем, что миграции применены, затем запускаем gunicorn
    startCommand: >
      bash -lc "python manage.py migrate --noinput &&
               gunicorn core.wsgi:application --bind 0.0.0.0:\$PORT --workers 3"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        # Оставьте ваш текущий DATABASE_URL как есть (в вашем файле он уже прописан).
        # Если нужно — перезапишите здесь либо через веб-интерфейс Render.
        value: "postgresql://postgres.fjqbhcmsqypevfbpzcxj:TrackerPass@aws-1-eu-north-1.pooler.supabase.com:5432/postgres"
      - key: SUPABASE_URL
        value: "https://fjqbhcmsqypevfbpzcxj.supabase.co"
      - key: SUPABASE_KEY
        value: "REDACTED_OR_YOUR_KEY"
      - key: REVALIDATION_SECRET
        value: ""
      - key: FRONTEND_URL
        value: "https://positive-theta.vercel.app"
