services:
  - type: web
    name: selfdev-tracker-backend
    env: python
    plan: free
    branch: main
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DATABASE_URL
        fromDatabase:
          name: selfdev-db
          property: connectionString
      - key: SUPABASE_URL
        fromSecret: SUPABASE_URL
      - key: SUPABASE_KEY
        fromSecret: SUPABASE_KEY
      - key: TELEGRAM_BOT_TOKEN
        fromSecret: TELEGRAM_BOT_TOKEN
      - key: TELEGRAM_BOT_NAME
        fromSecret: TELEGRAM_BOT_NAME

databases:
  - name: selfdev-db
    plan: free
    databaseName: selfdev
    user: selfdev_user