# Generated by Django 5.2.7 on 2025-12-23 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_add_data_field_to_postrevision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postrevision',
            name='data',
        ),
    ]
