# Generated by Django 5.2.5 on 2025-10-03 19:28

import blog.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_postattachment_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaLibrary',
            fields=[
            ],
            options={
                'verbose_name': 'Медиа библиотека',
                'verbose_name_plural': 'Медиа библиотека',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.postattachment',),
        ),
        migrations.AddField(
            model_name='post',
            name='content_json',
            field=models.JSONField(blank=True, null=True, verbose_name='Content JSON'),
        ),
        migrations.AlterField(
            model_name='postattachment',
            name='file',
            field=models.FileField(storage=blog.storages.SupabaseStorage(), upload_to='post_attachments'),
        ),
    ]
