# Generated by Django 5.2.5 on 2025-10-12 09:54

import django_ckeditor_5.fields
import django_summernote.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postrevision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_json',
        ),
        migrations.RemoveField(
            model_name='postattachment',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='postattachment',
            name='file',
            field=models.FileField(upload_to=django_summernote.utils.uploaded_filepath),
        ),
    ]
