# Generated by Django 5.2.5 on 2025-08-31 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='progresstable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyprogress',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='tables.progresstable'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyprogress',
            unique_together={('table', 'date')},
        ),
    ]
