# Generated by Django 5.2.7 on 2025-11-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprogress',
            name='mood',
            field=models.IntegerField(blank=True, choices=[(1, '😢'), (2, '😞'), (3, '😐'), (4, '😊'), (5, '😁')], null=True, verbose_name='Настроение'),
        ),
        migrations.AddField(
            model_name='dailyprogress',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Заметки'),
        ),
        migrations.AddField(
            model_name='progresstable',
            name='calendar_enabled',
            field=models.BooleanField(default=True, verbose_name='Включить календарь'),
        ),
        migrations.AddField(
            model_name='progresstable',
            name='default_view',
            field=models.CharField(choices=[('month', 'Месяц'), ('week', 'Неделя'), ('day', 'День')], default='month', max_length=20, verbose_name='Вид по умолчанию'),
        ),
    ]
