# Generated by Django 5.2.5 on 2025-01-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='supabase_uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]