# Generated by Django 5.2.5 on 2025-09-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_telegram_data_customuser_telegram_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telegram_data',
            field=models.JSONField(blank=True, default=dict, help_text='Сырые данные, которые вернул Telegram Login Widget'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, help_text='ID пользователя Telegram', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='username из Telegram', max_length=255, null=True),
        ),
    ]
