# Generated by Django 5.2.7 on 2025-12-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_customuser_avatar_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='max_tables',
            field=models.PositiveIntegerField(default=3, help_text='Максимальное количество таблиц, которые пользователь может создать'),
        ),
    ]
