# Generated by Django 5.2.7 on 2025-12-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_max_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='max_tables',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tables_limit',
            field=models.IntegerField(blank=True, default=1, help_text='Максимум таблиц (число), -1 = неограниченно', null=True),
        ),
    ]
