# Generated by Django 5.2.7 on 2025-12-23 06:12

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userprofile_max_tables_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTableLimitsProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Лимиты таблиц',
                'verbose_name_plural': 'Лимиты таблиц',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tables_limit',
            field=models.IntegerField(blank=True, default=1, help_text='Максимум таблиц. -1 = неограниченно.', null=True),
        ),
    ]
